/** CREACION BD LINEAS DE METRO **/
DROP DATABASE IF EXISTS BD_LINEAS_METRO;
CREATE DATABASE IF NOT EXISTS BD_LINEAS_METRO;
USE BD_LINEAS_METRO;


/** CREACION TABLA ENTIDAD LINEA **/
DROP TABLE IF EXISTS LINEAS;
CREATE TABLE IF NOT EXISTS LINEAS
(
	ID_LINEA INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
	COLOR VARCHAR(70) NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	FECHA_INI DATE NOT NULL,
	
	UNIQUE INDEX AK_COLOR (COLOR)
) ENGINE INNODB;


/** CREACION TABLA ENTIDAD ESTACION **/
DROP TABLE IF EXISTS ESTACIONES;
CREATE TABLE IF NOT EXISTS ESTACIONES
(
	COD_ESTACION CHAR(6) NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	CALLE VARCHAR (100) NOT NULL,
	SUPERFICIE FLOAT UNSIGNED NOT NULL,
	ANDENES INT UNSIGNED NOT NULL,
	
	PRIMARY KEY (COD_ESTACION),
	
	INDEX AK_NOMBRE (NOMBRE)
) ENGINE INNODB;


/** CREACION TABLA RELACION LINEAS ESTA_FORMADA POR ESTACIONES **/
DROP TABLE IF EXISTS ESTACIONES_LINEAS;
CREATE TABLE IF NOT EXISTS ESTACIONES_LINEAS
(
	COD_ESTACION CHAR(6) NOT NULL,
	ID_LINEA INT UNSIGNED NOT NULL,
	NUM_ORDEN CHAR(6) NOT NULL,
	
	PRIMARY KEY (COD_ESTACION, ID_LINEA),
	
	FOREIGN KEY (COD_ESTACION) REFERENCES ESTACIONES(COD_ESTACION)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	INDEX FK_ESTACION (COD_ESTACION),
	
	FOREIGN KEY (ID_LINEA) REFERENCES LINEAS(ID_LINEA)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	INDEX FK_LINEA (ID_LINEA)
) ENGINE INNODB;

/** CREACION TABLA ENTIDAD PUERTA CON INTEGRIDAD REFERENCIAL SOBRE ESTACION**/
DROP TABLE IF EXISTS PUERTAS;
CREATE TABLE IF NOT EXISTS PUERTAS
(
	NUMERO INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
	CALLE VARCHAR(100) NOT NULL,
	SUPERFICIE FLOAT UNSIGNED NOT NULL,
	COD_ESTACION CHAR(6) NOT NULL,
	
	FOREIGN KEY (COD_ESTACION) REFERENCES ESTACIONES(COD_ESTACION)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	UNIQUE INDEX FK_ESTACION (COD_ESTACION)
) ENGINE INNODB;


/** CREACION TABLA ENTIDAD TREN **/
DROP TABLE IF EXISTS TRENES;
CREATE TABLE IF NOT EXISTS TRENES
(
	NUMERO INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	MODELO VARCHAR (100) NOT NULL,
	INI_SERVICIO DATE NOT NULL,
	ESTADO ENUM('ACTIVO', 'REPARACION'),
	VAGONES INT UNSIGNED NOT NULL DEFAULT 5,
	AFORO INT UNSIGNED NOT NULL,
	LINEA INT UNSIGNED,
	
	FOREIGN KEY (LINEA) REFERENCES LINEAS(ID_LINEA)
		ON DELETE SET NULL
		ON UPDATE CASCADE,
	UNIQUE INDEX FK_LINEA (LINEA)
) ENGINE INNODB;


/** CREACION TABLA ENTIDAD EMPLEADO **/
DROP TABLE IF EXISTS EMPLEADOS;
CREATE TABLE IF NOT EXISTS EMPLEADOS
(
	DNI CHAR(9) NOT NULL PRIMARY KEY,
	NSS CHAR(12) NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	SALARIO FLOAT NOT NULL DEFAULT 1200.0,
	DIRECCION VARCHAR(150) NOT NULL,
	FECHA_INGRESO DATE NOT NULL,
	SUPERVISOR CHAR(9) NOT NULL,
	
	ESTACION CHAR(6) NOT NULL,
	
	FOREIGN KEY (ESTACION) REFERENCES ESTACIONES(COD_ESTACION)
		ON DELETE RESTRICT
		ON UPDATE CASCADE,
	UNIQUE INDEX FK_ESTACION (ESTACION),
	
	FOREIGN KEY (SUPERVISOR) REFERENCES EMPLEADOS(DNI)
		ON DELETE RESTRICT
		ON UPDATE CASCADE,
	INDEX FK_SUPERVISOR (SUPERVISOR) 
) ENGINE INNODB;


/** CRECION SUBENTIDAD JEFE ESTACION **/
DROP TABLE IF EXISTS JEFES_ESTACION;
CREATE TABLE IF NOT EXISTS JEFES_ESTACION
(
	ID_JEFE INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
	DNI CHAR(9) NOT NULL,
	FECHA DATE NOT NULL,
	PRIMA FLOAT NOT NULL,
	ESTACION CHAR(6) NOT NULL,
	
	FOREIGN KEY (ESTACION) REFERENCES ESTACIONES(COD_ESTACION)
		ON DELETE RESTRICT
		ON UPDATE CASCADE,
	UNIQUE INDEX FK_ESTACION_AL_CARGO (ESTACION),
	
	FOREIGN KEY (DNI) REFERENCES EMPLEADOS(DNI)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	INDEX FK_DNI (DNI)
) ENGINE INNODB;


/** CREACION SUBENTIDAD MAQUINISTA **/
DROP TABLE IF EXISTS MAQUINISTAS;
CREATE TABLE IF NOT EXISTS MAQUINISTAS
(
	ID_MAQUINISTA INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
	DNI CHAR(9) NOT NULL,
	TURNO ENUM('MAÑANA', 'TARDE', 'NOCHE') NOT NULL,
	LINEA INT UNSIGNED NOT NULL,
	
	FOREIGN KEY (LINEA) REFERENCES LINEAS(ID_LINEA)
		ON DELETE RESTRICT
		ON UPDATE CASCADE,
	UNIQUE INDEX FK_LINEA_ASIGNADA(LINEA),
	
	FOREIGN KEY (DNI) REFERENCES EMPLEADOS(DNI)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	INDEX FK_DNI (DNI)
) ENGINE INNODB;
